/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SahimIcons {
  SahimIcons._();

  static const _kFontFam = 'SahimIcons';
  static const String? _kFontPkg = null;

  static const IconData compassion__love__care__empathy = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData compassion__love__care__empathy_1 = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData donation__charity__volunteer__community = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData donation__charity__volunteer__community_1 = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData gift__donation__give__charity = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData gift__donation__give__charity_1 = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData group = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData group_1 = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData group_2 = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData group_3 = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData happiness__smile__kindness__love = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData happiness__smile__kindness__love_1 = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData healing__spiritual__charity__mindfulness = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData healing__spiritual__charity__mindfulness_1 = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData help__hand__support__charity = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData help__hand__support__charity_1 = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData human__love__head__charity = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData kindness__love__charity__give = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData kindness__love__charity__give_1 = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData peace__symbol__hope__faith = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData people__love__family__happy = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData people__love__family__happy_1 = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData praying__religion__charity__faith = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData praying__religion__charity__faith_1 = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData shelter__charity__volunteer__social = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData shelter__charity__volunteer__social_1 = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData shelter__community__charity__volunteer = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData shelter__community__charity__volunteer_1 = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData support__hand__care__charity = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData support__hand__care__charity_1 = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData unity__teamwork__solidarity__community = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData unity__teamwork__solidarity__community_1 = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData volunteer__charity__community__compassion = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData volunteer__charity__community__compassion_1 = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData awareness__ribbon__cancer__charity = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData awareness__ribbon__cancer__charity_1 = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData blood__donation__transfusion__volunteer = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData charity__care__volunteer__support = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData charity__care__volunteer__support_1 = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData ok = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData religious_islam = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData tooth = IconData(0xf5c9, fontFamily: _kFontFam);
  static const IconData lungs = IconData(0xf604, fontFamily: _kFontFam);
  static const IconData kaaba = IconData(0xf66b, fontFamily: _kFontFam);
  static const IconData mosque = IconData(0xf678, fontFamily: _kFontFam);
  static const IconData cat = IconData(0xf6be, fontFamily: _kFontFam);
}
